name: CleanReact Lint & Unit-Test
on: [push]
jobs:
    check-repo:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16.13.x
                  cache: npm

            - name: Install
              run: npm ci

            - name: ESLint
              run: npx eslint 'src/**'

            - name: Test-CI
              run: npm run test:ci
