name: CleanReact Lint & Unit-Test
on: [push]
jobs:
    install-dependencies:
        - name: Checkout
          runs-on: ubuntu-latest
          uses: actions/checkout@v3

        - name: Setup node
          uses: actions/setup-node@v3
          with:
              node-version: 16.13.x
              cache: npm
        steps:
            - name: Install
              run: npm ci

    run-lint:
        needs: install-dependencies
        name: ESLint

        steps:
            - name: run ESLint
              run: npx eslint 'src/**'

    run-unit-tests:
        needs: install-dependencies
        name: Unit-Test

        steps:
            - name: run test:ci
              run: npm run test:ci
