name: ESLint & Unit-Test
on: [push]
jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3

            - name: setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16.13.x
                  cache: npm

            - name: install
              run: npm ci
    lint:
        runs-on: ubuntu-latest
        needs: install
        steps:
            - name: ESLint
              run: npx eslint 'src/**'

    test:
        runs-on: ubuntu-latest
        needs: install
        steps:
            - name: test:ci
              run: npm run test:ci
