name: CleanReact Lint & Test
on: [push]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - run: npx eslint 'src/**'
    test:
        runs-on: ubuntu-latest
        steps:
            - run: npm run test:ci
