name: ESLint & Unit-Test
on: [push]
jobs:
    eslint:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3

            - name: setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16.13.x
                  cache: npm

            - name: install
              run: npm ci

            - name: ESLint
              run: npx eslint 'src/**'

    unit-test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3

            - name: setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16.13.x
                  cache: npm

            - name: install
              run: npm ci

            - name: Coveralls
              run: npm run test:coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.COVERALLS_KEY }}
